#!/usr/bin/env node

var request = require('request');
var notify= require('libnotify');

function isLinuxSupported(appid) {
  request({
    url: "http://store.steampowered.com/api/appdetails",
    qs: {"appids": appid}
  }, function (error, response, body) {
    if (!error && response.statusCode == 200) {
      var completeData = JSON.parse(body);
      var data = completeData[Object.keys(completeData)[0]].data;
      console.log("Linux supported for " + data.name + " ? " + data.platforms.linux);
      if (data.platforms.linux === true) {
	notify.notify("Supported !", {
	  title: "Steam checker - " + data.name,
	  image: "/usr/share/icons/gnome/48x48/status/starred.png"
	});
      } else {
	/*
	   notify.notify("Still not supported", {
	   title: "Steam checker - " + data.name,
	   image: "/usr/share/icons/gnome/48x48/status/dialog-error.png"
	   });
	   */
      }
    } else {
      console.log(response.statusCode);
      console.log(body);
    }
  });
}

function launch(appid, interval) {
  request({
    url: "http://store.steampowered.com/api/appdetails",
    qs: {"appids": appid}
  }, function (error, response, body) {
    if (!error && response.statusCode == 200) {
      var completeData = JSON.parse(body);
      var data = completeData[Object.keys(completeData)[0]].data;
      notify.notify("Beginning check for " + data.name +  " every " + interval + " seconds", {
	title: "Steam checker"
      });
    }
  });
  setInterval(function() {
    isLinuxSupported(appid);
  }, 1000 * interval);
}

function usage() {
  console.error("./checker [-i interval_of_checking_in_seconds] appid");
  console.error("Example: ./checker -i 30 255220");
}

var interval = 30;
(function() {
  var index = 2;
  if (process.argv.length <= 2) {
    usage();
    process.exit();
  }
  while (index < process.argv.length) {
    if (process.argv[index] == "--help") {
      usage();
      process.exit();
    } else if (process.argv[index] == "-i") {
      interval = parseInt(process.argv[index + 1]);
      index++;
    } else {
      appid = parseInt(process.argv[index]);
    }
    index++;
  }
  if (isNaN(interval)) {
    console.error("Interval have to be an integer.");
    process.exit();
  }

  if (isNaN(appid)) {
    console.error("Appid have to be a number.");
    process.exit();
}
launch(appid, interval);
/*
console.log("appid : " + appid)
console.log("interval : " + interval)
*/
})();
